version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sherlock-backend
    volumes:
      - ./backend/data:/app/data
    environment:
      - PORT=8000
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sherlock-frontend
    environment:
      - VITE_API_URL=https://sherlock-backend.arturoalvarez.site
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - backend

networks:
  default:
    name: sherlock-network
